schema: "classroom50/repo-config/v1"
classroom: "cprog"
assignment: "i-know-flowchart"
owner:
  username: "Ibsen0512"
  id: 64329165
  accepted_at: "2026-09-04T20:07:17Z"
source:
  owner: "geko-crooms"
  owner_id: 316422449
  repo: "i-know-flowchart"
  branch: "main"
